name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: install ndk
      run: 
        echo y | sdkmanager "tools"
        echo y | sdkmanager "platform-tools"
        echo y | sdkmanager "tools"
        echo y | sdkmanager "build-tools;30.0.3"
        echo y | sdkmanager "platforms;android-30"
        echo y | sdkmanager "ndk-bundle"
        echo y | sdkmanager "ndk;21.3.6528147"
        echo y | sdkmanager "cmake;3.10.2.4988404"

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: clean Gradle cache
      run: ./gradlew clean
      
    - name: Build with Gradle
      run: ./gradlew assembleRelease
          
    - name: Build with Gradle
      run: ./gradlew assembleDebug
      
    - uses: actions/upload-artifact@v2
      with:
        name: release-apk
        path: |
          ${{github.workspace}}/build/outputs/apk/release/*.apk
          
    - uses: actions/upload-artifact@v2
      with:
        name: debug-apk
        path: |
          ${{github.workspace}}/build/outputs/apk/debug/*.apk
